#!/usr/bin/env bash

set -e

pacman -Su
pacman -S --needed autoconf automake git gzip make ${MINGW_PACKAGE_PREFIX}-gcc ${MINGW_PACKAGE_PREFIX}-cmake ${MINGW_PACKAGE_PREFIX}-libtool patch tar xz

if [ ! -d nrsc5 ]; then
    git clone https://github.com/fventuri/nrsc5
    cd nrsc5
else
    cd nrsc5
    git pull
fi
mkdir build
cd build
SDR_DRIVER="$1"; shift
case "$SDR_DRIVER" in
    rtlsdr)
        cmake -G "MSYS Makefiles" \
            -D USE_STATIC=ON \
            -D SDR_DRIVER="$SDR_DRIVER" \
            -D USE_SYSTEM_LIBUSB=OFF \
            -D USE_SYSTEM_RTLSDR=OFF \
            -D USE_SYSTEM_LIBAO=OFF \
            -D USE_SYSTEM_FFTW=OFF \
            -D USE_SSE=ON \
            -D CMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
            ..
        ;;
    *)
        cmake -G "MSYS Makefiles" \
            -D USE_STATIC=ON \
            -D SDR_DRIVER="$SDR_DRIVER" \
            -D USE_SYSTEM_LIBAO=OFF \
            -D USE_SYSTEM_FFTW=OFF \
            -D USE_SSE=ON \
            -D CMAKE_INSTALL_PREFIX=${MINGW_PREFIX} \
            ..
        ;;
esac
make $*
make install
