name: CI

#on: [push, pull_request]
on:
  workflow_dispatch:
    inputs:
      sdr_driver:
        description: 'SDR driver (rtlsdr, sdrplay, soapy)'
        required: true
        default: 'rtlsdr'

jobs:
  ubuntu-build-rtlsdr:
    name: Ubuntu CI RTL-SDR
    if github.event.inputs.sdr_driver == 'rtlsdr'
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y libao-dev libfftw3-dev librtlsdr-dev python3-pyaudio
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Compile
        working-directory: build
        run: make -j3
      - name: Install
        working-directory: build
        run: |
          sudo make install
          sudo ldconfig
      - name: Test
        run: |
          xz -d < support/sample.xz > sample
          nrsc5 -r sample -o sample.wav 0 2> sample.log
          cat sample.log
          grep -q "You're Listening to Q" sample.log
          cat sample | nrsc5 -r - -o sample.wav 0 2> sample.log
          grep -q "You're Listening to Q" sample.log
          support/cli.py -r sample 0
          cat sample | support/cli.py -r - 0
      - name: Windows cross-compile
        run: |
          sudo apt-get install -y mingw-w64
          support/win-cross-compile 32 rtlsdr
          support/win-cross-compile 64 rtlsdr
  macos-build-rtlsdr:
    name: MacOS CI RTL-SDR
    if github.event.inputs.sdr_driver == 'rtlsdr'
    runs-on: macos-10.15
    steps:
      - name: Install dependencies
        run: |
          brew install autoconf automake libao fftw librtlsdr portaudio
          pip3 install pyaudio
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Compile
        working-directory: build
        run: make -j3
      - name: Install
        working-directory: build
        run: make install
      - name: Test
        run: |
          xz -d < support/sample.xz > sample
          nrsc5 -r sample -o sample.wav 0 2> sample.log
          cat sample.log
          grep -q "You're Listening to Q" sample.log
          cat sample | nrsc5 -r - -o sample.wav 0 2> sample.log
          grep -q "You're Listening to Q" sample.log
          support/cli.py -r sample 0
          cat sample | support/cli.py -r - 0
      - name: Windows cross-compile
        run: |
          brew cask install xquartz wine-stable
          brew install mingw-w64
          support/win-cross-compile 32 rtlsdr
          support/win-cross-compile 64 rtlsdr

  ubuntu-build-sdrplay:
    name: Ubuntu CI SDRplay API 3.X
    if github.event.inputs.sdr_driver == 'sdrplay'
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -y libao-dev libfftw3-dev python3-pyaudio
      - name: Install SDRplay API 3.X
        run: |
          curl -s -S -O https://www.sdrplay.com/software/SDRplay_RSP_API-Linux-3.07.1.run
          echo "PATH: $PATH"
          #sh SDRplay_RSP_API-Linux-3.07.1.run
      #- name: Checkout code
      #  uses: actions/checkout@v2
      #- name: Configure
      #  run: |
      #    mkdir build
      #    cd build
      #    cmake ..
      #- name: Compile
      #  working-directory: build
      #  run: make -j3
      #- name: Install
      #  working-directory: build
      #  run: |
      #    sudo make install
      #    sudo ldconfig
      #- name: Windows cross-compile
      #  run: |
      #    sudo apt-get install -y mingw-w64
      #    support/win-cross-compile 32 sdrplay
      #    support/win-cross-compile 64 sdrplay
